# Data Loading

In [2]:
! pip install pandas

Collecting pandas
  Downloading pandas-2.2.3-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.2.5-cp312-cp312-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\wwwsu\desktop\all folders\assessment_fleetpanda\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\wwwsu\desktop\all folders\assessment_fleetpanda\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.2.3-cp312-cp312-win_amd64.whl (11.5 MB)
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
    --------------------------------------- 0.3/11.5 MB ? eta -:--:--
   --- ------------------------------------ 1.0/11.5 MB 2.2 MB/s eta 0:00:05
   --------- ------------------------------ 2.6/11.5 MB 4.0 MB/s eta 0:00:03
   -------------------- ------------------- 6.0/11.5 MB 7.2 MB/s eta 0:00:01
   ---------------------------------------  11.3/11.5 MB 11.2 MB/s eta 0:00:01
   ---------------------------------------- 11.5/11.5 MB 10.7 MB/s eta 0:00:00
Downloading numpy-2.2.5-cp312-cp312-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.6 MB ? eta -:--:--
   ---------------- ----------------------- 5.2/12.6 MB 21.3 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/12.6 MB 41.0 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/12.6 MB 41.0 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/12.6 MB 41.0 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/12.6 MB 41.0 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/12.6 MB 41.0 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/12.6 MB 41.0 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/12.6 MB 41.0 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/12.6 MB 41.0 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/12.6 MB 41.0 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/12.6 MB 41.0 MB/s eta 0:00:01
   -------------------------------------- - 12.1/12.6 MB 4.9 MB/s eta 0:00:01
   -------------------------------------- - 12.1/12.6 MB 4.9 MB/s eta 0:00:01
   -------------------------------------- - 12.1/12.6 MB 4.9 MB/s eta 0:00:01
   -------------------------------------- - 12.1/12.6 MB 4.9 MB/s eta 0:00:01
   -------------------------------------- - 12.1/12.6 MB 4.9 MB/s eta 0:00:01
   -------------------------------------- - 12.3/12.6 MB 3.5 MB/s eta 0:00:01
   -------------------------------------- - 12.3/12.6 MB 3.5 MB/s eta 0:00:01
   -------------------------------------- - 12.3/12.6 MB 3.5 MB/s eta 0:00:01
   -------------------------------------- - 12.3/12.6 MB 3.5 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.6 MB 2.9 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.6 MB 2.9 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 2.6 MB/s eta 0:00:00
Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: pytz, tzdata, numpy, pandas

   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ---------------------------------------- 4/4 [pandas]

Successfully installed numpy-2.2.5 pandas-2.2.3 pytz-2025.2 tzdata-2025.2

In [3]:
!pip install matplotlib
!pip install seaborn
! pip install numpy

Collecting matplotlib
  Downloading matplotlib-3.10.3-cp312-cp312-win_amd64.whl.metadata (11 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.2-cp312-cp312-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.58.0-cp312-cp312-win_amd64.whl.metadata (106 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.4.8-cp312-cp312-win_amd64.whl.metadata (6.3 kB)
Requirement already satisfied: numpy>=1.23 in c:\users\wwwsu\desktop\all folders\assessment_fleetpanda\.venv\lib\site-packages (from matplotlib) (2.2.5)
Requirement already satisfied: packaging>=20.0 in c:\users\wwwsu\desktop\all folders\assessment_fleetpanda\.venv\lib\site-packages (from matplotlib) (25.0)
Collecting pillow>=8 (from matplotlib)
  Downloading pillow-11.2.1-cp312-cp312-win_amd64.whl.metadata (9.1 kB)
Collecting pyparsing>=2.3.1 (from matplotlib)
  Downloading pyparsing-3.2.3-py3-none-any.whl.metadata (5.0 kB)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\wwwsu\desktop\all folders\assessment_fleetpanda\.venv\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\wwwsu\desktop\all folders\assessment_fleetpanda\.venv\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Downloading matplotlib-3.10.3-cp312-cp312-win_amd64.whl (8.1 MB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.1 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.1 MB 885.6 kB/s eta 0:00:09
   --- ------------------------------------ 0.8/8.1 MB 884.1 kB/s eta 0:00:09
   --- ------------------------------------ 0.8/8.1 MB 884.1 kB/s eta 0:00:09
   ----- ---------------------------------- 1.0/8.1 MB 915.5 kB/s eta 0:00:08
   ------ --------------------------------- 1.3/8.1 MB 945.5 kB/s eta 0:00:08
   ------- -------------------------------- 1.6/8.1 MB 953.2 kB/s eta 0:00:07
   --------- ------------------------------ 1.8/8.1 MB 967.9 kB/s eta 0:00:07
   ---------- ----------------------------- 2.1/8.1 MB 987.1 kB/s eta 0:00:07
   ----------- ---------------------------- 2.4/8.1 MB 1.0 MB/s eta 0:00:06
   ------------ --------------------------- 2.6/8.1 MB 1.0 MB/s eta 0:00:06
   -------------- ------------------------- 2.9/8.1 MB 1.0 MB/s eta 0:00:06
   -------------- ------------------------- 2.9/8.1 MB 1.0 MB/s eta 0:00:06
   --------------- ------------------------ 3.1/8.1 MB 1.0 MB/s eta 0:00:05
   ---------------- ----------------------- 3.4/8.1 MB 1.0 MB/s eta 0:00:05
   ------------------ --------------------- 3.7/8.1 MB 1.1 MB/s eta 0:00:05
   ------------------- -------------------- 3.9/8.1 MB 1.1 MB/s eta 0:00:04
   -------------------- ------------------- 4.2/8.1 MB 1.1 MB/s eta 0:00:04
   ---------------------- ----------------- 4.5/8.1 MB 1.1 MB/s eta 0:00:04
   ----------------------- ---------------- 4.7/8.1 MB 1.1 MB/s eta 0:00:04
   ------------------------ --------------- 5.0/8.1 MB 1.1 MB/s eta 0:00:03
   ------------------------- -------------- 5.2/8.1 MB 1.1 MB/s eta 0:00:03
   --------------------------- ------------ 5.5/8.1 MB 1.1 MB/s eta 0:00:03
   ---------------------------- ----------- 5.8/8.1 MB 1.1 MB/s eta 0:00:03
   ----------------------------- ---------- 6.0/8.1 MB 1.1 MB/s eta 0:00:02
   ------------------------------- -------- 6.3/8.1 MB 1.1 MB/s eta 0:00:02
   -------------------------------- ------- 6.6/8.1 MB 1.1 MB/s eta 0:00:02
   --------------------------------- ------ 6.8/8.1 MB 1.1 MB/s eta 0:00:02
   ----------------------------------- ---- 7.1/8.1 MB 1.1 MB/s eta 0:00:01
   ------------------------------------ --- 7.3/8.1 MB 1.1 MB/s eta 0:00:01
   ------------------------------------- -- 7.6/8.1 MB 1.1 MB/s eta 0:00:01
   -------------------------------------- - 7.9/8.1 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 1.1 MB/s eta 0:00:00
Downloading contourpy-1.3.2-cp312-cp312-win_amd64.whl (223 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.58.0-cp312-cp312-win_amd64.whl (2.2 MB)
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.2 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.2 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.2 MB ? eta -:--:--
   --------- ------------------------------ 0.5/2.2 MB 429.7 kB/s eta 0:00:04
   --------- ------------------------------ 0.5/2.2 MB 429.7 kB/s eta 0:00:04
   -------------- ------------------------- 0.8/2.2 MB 472.3 kB/s eta 0:00:04
   -------------- ------------------------- 0.8/2.2 MB 472.3 kB/s eta 0:00:04
   ------------------ --------------------- 1.0/2.2 MB 529.6 kB/s eta 0:00:03
   ------------------ --------------------- 1.0/2.2 MB 529.6 kB/s eta 0:00:03
   ----------------------- ---------------- 1.3/2.2 MB 559.2 kB/s eta 0:00:02
   ---------------------------- ----------- 1.6/2.2 MB 582.5 kB/s eta 0:00:02
   ---------------------------- ----------- 1.6/2.2 MB 582.5 kB/s eta 0:00:02
   --------------------------------- ------ 1.8/2.2 MB 602.6 kB/s eta 0:00:01
   --------------------------------- ------ 1.8/2.2 MB 602.6 kB/s eta 0:00:01
   ------------------------------------- -- 2.1/2.2 MB 614.7 kB/s eta 0:00:01
   ---------------------------------------- 2.2/2.2 MB 615.1 kB/s eta 0:00:00
Downloading kiwisolver-1.4.8-cp312-cp312-win_amd64.whl (71 kB)
Downloading pillow-11.2.1-cp312-cp312-win_amd64.whl (2.7 MB)
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.7 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.7 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.7 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.7 MB 541.6 kB/s eta 0:00:04
   ------- -------------------------------- 0.5/2.7 MB 541.6 kB/s eta 0:00:04
   ----------- ---------------------------- 0.8/2.7 MB 568.6 kB/s eta 0:00:04
   --------------- ------------------------ 1.0/2.7 MB 599.0 kB/s eta 0:00:03
   --------------- ------------------------ 1.0/2.7 MB 599.0 kB/s eta 0:00:03
   ------------------- -------------------- 1.3/2.7 MB 621.2 kB/s eta 0:00:03
   ------------------- -------------------- 1.3/2.7 MB 621.2 kB/s eta 0:00:03
   ----------------------- ---------------- 1.6/2.7 MB 640.3 kB/s eta 0:00:02
   ----------------------- ---------------- 1.6/2.7 MB 640.3 kB/s eta 0:00:02
   --------------------------- ------------ 1.8/2.7 MB 649.4 kB/s eta 0:00:02
   ------------------------------- -------- 2.1/2.7 MB 659.8 kB/s eta 0:00:01
   ------------------------------- -------- 2.1/2.7 MB 659.8 kB/s eta 0:00:01
   ----------------------------------- ---- 2.4/2.7 MB 664.5 kB/s eta 0:00:01
   ----------------------------------- ---- 2.4/2.7 MB 664.5 kB/s eta 0:00:01
   ---------------------------------------- 2.7/2.7 MB 660.5 kB/s eta 0:00:00
Downloading pyparsing-3.2.3-py3-none-any.whl (111 kB)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib

   ---------------------------------------- 0/7 [pyparsing]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ---------------------------- ----------- 5/7 [contourpy]
   ---------------------------- ----------- 5/7 [contourpy]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------------- 7/7 [matplotlib]

Successfully installed contourpy-1.3.2 cycler-0.12.1 fonttools-4.58.0 kiwisolver-1.4.8 matplotlib-3.10.3 pillow-11.2.1 pyparsing-3.2.3
Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\wwwsu\desktop\all folders\assessment_fleetpanda\.venv\lib\site-packages (from seaborn) (2.2.5)
Requirement already satisfied: pandas>=1.2 in c:\users\wwwsu\desktop\all folders\assessment_fleetpanda\.venv\lib\site-packages (from seaborn) (2.2.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\wwwsu\desktop\all folders\assessment_fleetpanda\.venv\lib\site-packages (from seaborn) (3.10.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\wwwsu\desktop\all folders\assessment_fleetpanda\.venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\wwwsu\desktop\all folders\assessment_fleetpanda\.venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\wwwsu\desktop\all folders\assessment_fleetpanda\.venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.58.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\wwwsu\desktop\all folders\assessment_fleetpanda\.venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\wwwsu\desktop\all folders\assessment_fleetpanda\.venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\wwwsu\desktop\all folders\assessment_fleetpanda\.venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\wwwsu\desktop\all folders\assessment_fleetpanda\.venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\wwwsu\desktop\all folders\assessment_fleetpanda\.venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\wwwsu\desktop\all folders\assessment_fleetpanda\.venv\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\wwwsu\desktop\all folders\assessment_fleetpanda\.venv\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\wwwsu\desktop\all folders\assessment_fleetpanda\.venv\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Installing collected packages: seaborn
Successfully installed seaborn-0.13.2
Requirement already satisfied: numpy in c:\users\wwwsu\desktop\all folders\assessment_fleetpanda\.venv\lib\site-packages (2.2.5)

In [4]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [77]:
## Loading dataset 
df = pd.read_csv(r'C:\Users\wwwsu\Desktop\All folders\Assessment_FleetPanda\data\raw\WA_Fn-UseC_-Telco-Customer-Churn.csv')

In [78]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

Most of the columns here are categorical. 
Even TotalCharges seems to be float in dataset which is object in real; we must convert that into float too

In [80]:
df.shape

(7043, 21)

## Exploratory Data Analysis

In [81]:
# Numerical statistics of the dataset
df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [82]:
# Categorical Statistics of the dataset
df.describe(include='object')

,customerID,gender,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,TotalCharges,Churn
count,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043
unique,7043,2,2,2,2,3,3,3,3,3,3,3,3,3,2,4,6531,2
top,3186-AJIEK,Male,No,No,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,20.2,No
freq,1,3555,3641,4933,6361,3390,3096,3498,3088,3095,3473,2810,2785,3875,4171,2365,11,5174

In [83]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [84]:
# Convert TotalCharges to numeric, coerce errors to NaN
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

# Count missing values per column
df.isna().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

## Target Distribution

In [85]:
# Check class balance for churn
counts = df['Churn'].value_counts()
percentages = df['Churn'].value_counts(normalize=True) * 100

imbalance_table = pd.DataFrame({
    'Count': counts,
    'Percentage (%)': percentages.round(2)
})
imbalance_table

       Count  Percentage (%)
Churn
No      5174           73.46
Yes     1869           26.54

## Data Cleaning

In [86]:
## Droping NaN values of TotalCharges
df.dropna(subset=['TotalCharges'], inplace=True)
df.isna().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [87]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7032 non-null   object
 1   gender            7032 non-null   object
 2   SeniorCitizen     7032 non-null   int64
 3   Partner           7032 non-null   object
 4   Dependents        7032 non-null   object
 5   tenure            7032 non-null   int64
 6   PhoneService      7032 non-null   object
 7   MultipleLines     7032 non-null   object
 8   InternetService   7032 non-null   object
 9   OnlineSecurity    7032 non-null   object
 10  OnlineBackup      7032 non-null   object
 11  DeviceProtection  7032 non-null   object
 12  TechSupport       7032 non-null   object
 13  StreamingTV       7032 non-null   object
 14  StreamingMovies   7032 non-null   object
 15  Contract          7032 non-null   object
 16  PaperlessBilling  7032 non-null   object
 17  PaymentMethod     7032 non-null   object
 18  MonthlyCharges    7032 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7032 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.2+ MB

In [88]:
# Remove customerID column
df = df.drop('customerID', axis=1)
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

CustomerID is a unique column which does not have any involvement in churn prediction so this column is removed.

In [89]:
## Separating the target varibale 
y = df['Churn'].map({'No': 0, 'Yes': 1})
X = df.drop('Churn', axis=1)

### Converting Categorical Variables to Numerical

In [90]:
# Identifying categorical columns
categorical_cols = X.select_dtypes(include=['object']).columns.tolist()
print(categorical_cols)

['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod']

Now these columns should be encoded numerically. For binary categorical varibale we use binary encoding and one hot encoding for other categorical varibale.

In [91]:
# Binary Encoding
binary_cols = ['Partner', 'Dependents', 'PhoneService', 'PaperlessBilling']

for col in binary_cols:
    X[col] = X[col].map({'Yes': 1, 'No':0})

In [92]:
# Exclude the binary columns already encoded
multi_cat_cols = [col for col in categorical_cols if col not in binary_cols]

print("Columns to one-hot encode:", multi_cat_cols)

Columns to one-hot encode: ['gender', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaymentMethod']

In [95]:
# One Hot Encoding
X = pd.get_dummies(X, columns=multi_cat_cols, drop_first=True, dtype=int)
X.head()

,SeniorCitizen,Partner,Dependents,tenure,PhoneService,PaperlessBilling,MonthlyCharges,TotalCharges,gender_Male,MultipleLines_No phone service,...,TechSupport_Yes,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,0,1,0,1,29.85,29.85,0,1,...,0,0,0,0,0,0,0,0,1,0
1,0,0,0,34,1,0,56.95,1889.50,1,0,...,0,0,0,0,0,1,0,0,0,1
2,0,0,0,2,1,1,53.85,108.15,1,0,...,0,0,0,0,0,0,0,0,0,1
3,0,0,0,45,0,0,42.30,1840.75,1,1,...,1,0,0,0,0,1,0,0,0,0
4,0,0,0,2,1,1,70.70,151.65,0,0,...,0,0,0,0,0,0,0,0,1,0

In [96]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 30 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   SeniorCitizen                          7032 non-null   int64
 1   Partner                                7032 non-null   int64
 2   Dependents                             7032 non-null   int64
 3   tenure                                 7032 non-null   int64
 4   PhoneService                           7032 non-null   int64
 5   PaperlessBilling                       7032 non-null   int64
 6   MonthlyCharges                         7032 non-null   float64
 7   TotalCharges                           7032 non-null   float64
 8   gender_Male                            7032 non-null   int64
 9   MultipleLines_No phone service         7032 non-null   int64
 10  MultipleLines_Yes                      7032 non-null   int64
 11  InternetService_Fiber optic            7032 non-null   int64
 12  InternetService_No                     7032 non-null   int64
 13  OnlineSecurity_No internet service     7032 non-null   int64
 14  OnlineSecurity_Yes                     7032 non-null   int64
 15  OnlineBackup_No internet service       7032 non-null   int64
 16  OnlineBackup_Yes                       7032 non-null   int64
 17  DeviceProtection_No internet service   7032 non-null   int64
 18  DeviceProtection_Yes                   7032 non-null   int64
 19  TechSupport_No internet service        7032 non-null   int64
 20  TechSupport_Yes                        7032 non-null   int64
 21  StreamingTV_No internet service        7032 non-null   int64
 22  StreamingTV_Yes                        7032 non-null   int64
 23  StreamingMovies_No internet service    7032 non-null   int64
 24  StreamingMovies_Yes                    7032 non-null   int64
 25  Contract_One year                      7032 non-null   int64
 26  Contract_Two year                      7032 non-null   int64
 27  PaymentMethod_Credit card (automatic)  7032 non-null   int64
 28  PaymentMethod_Electronic check         7032 non-null   int64
 29  PaymentMethod_Mailed check             7032 non-null   int64
dtypes: float64(2), int64(28)
memory usage: 1.7 MB

In [ ]:
!pip install scikit-learn

### Train Test Split

In [98]:
from sklearn.model_selection import train_test_split

# Splitting data : 70% train, 30% test
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

In [99]:
# Check the shape of splits
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)

X_train shape: (4922, 30)
X_test shape: (2110, 30)

## Saving split dataset to files

In [103]:
import pickle

with open('X_train.pkl', 'wb') as f:
    pickle.dump(X_train, f)

with open('X_test.pkl', 'wb') as f:
    pickle.dump(X_test, f)

with open('y_train.pkl', 'wb') as f:
    pickle.dump(y_train, f)

with open('y_test.pkl', 'wb') as f:
    pickle.dump(y_test, f)